# -*- coding: utf-8 -*-
"""carPricePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFJPDy-XxoQMOh_2rMGL2z0v91dnP2KS
"""



"""#Car Price Prediction using Multiple Linear Regression
Name:Arshad Ibrahim Tamboli
"""

#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#upload dataset
from google.colab import files

uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])

df.head()

#basic data Information
print("Number of observations:", df.shape[0])
print("Number of variables:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

#check duplicate rows
print("Number of Duplicate rows:",
      df.duplicated().sum())

#data cleaning
df["max_power"] = pd.to_numeric(df["max_power"], errors="coerce")

print(df.dtypes)

#remove missing values
df = df.dropna(subset=[
    "selling_price",
    "year",
    "km_driven",
    "mileage(km/ltr/kg)",
    "engine",
    "max_power",
    "seats"
])

print(df.isnull().sum())

#select features
X = df[
    [
        "year",
        "km_driven",
        "mileage(km/ltr/kg)",
        "engine",
        "max_power",
        "seats"
    ]
]

y = df["selling_price"]

#price distribution
plt.figure(figsize=(8,5))

sns.histplot(df["selling_price"], kde=True)

plt.title("Distribution of Car Selling Prices")
plt.xlabel("Selling Price")
plt.ylabel("Frequency")

plt.show()

#year vs selling price
plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df["year"],
    y=df["selling_price"]
)

plt.title("Year vs Car Selling Price")
plt.xlabel("Manufacturing Year")
plt.ylabel("Selling Price")

plt.show()

#kilometres driven vs price
plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df["km_driven"],
    y=df["selling_price"]
)

plt.title("Kilometres Driven vs Car Selling Price")
plt.xlabel("Kilometres Driven")
plt.ylabel("Selling Price")

plt.show()

#engine vs price
plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df["engine"],
    y=df["selling_price"]
)

plt.title("Engine vs Car Selling Price")
plt.xlabel("Engine Capacity")
plt.ylabel("Selling Price")

plt.show()

#correlation heatmap
plt.figure(figsize=(9,6))

sns.heatmap(
    X.join(y).corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()

#train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

#multiple linear regression model
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

#make prediction
y_pred = model.predict(X_test)

#actual vs predicted peice
result = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})

display(result.head(20))

#calculate r^2
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

from sklearn.metrics import mean_squared_error, mean_absolute_error

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("RMSE:", rmse)
print("MAE:", mae)

#adjusted R^2
n = X_test.shape[0]
p = X_test.shape[1]

adjusted_r2 = 1 - ((1 - r2) * (n - 1) / (n - p - 1))

print("Adjusted R²:", adjusted_r2)

#display all results
print("Model Performance")
print("------------------------")
print("R² Score:", r2)
print("Adjusted R²:", adjusted_r2)
print("RMSE:", rmse)
print("MAE:", mae)

#model coefficient
print("Intercept:", model.intercept_)

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

display(coefficients)

#actual vs predicted graph
plt.figure(figsize=(8,5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Selling Price")
plt.ylabel("Predicted Selling Price")
plt.title("Actual vs Predicted Car Prices")

plt.show()

#predict a value
new_car = [[
    2018,      # year
    50000,     # km_driven
    20.0,      # mileage
    1200,      # engine
    85,        # max_power
    5          # seats
]]

predicted_price = model.predict(new_car)

print("Predicted Car Selling Price:", predicted_price[0])

"""Conclusion:In this project, Multiple Linear Regression was used to predict the selling price of used cars based on features such as manufacturing year, kilometres driven, mileage, engine capacity, maximum power and number of seats. The dataset was cleaned and analyzed using exploratory data analysis. The model was evaluated using R², Adjusted R², RMSE and MAE. The project demonstrates how machine learning can be used to estimate used-car prices from vehicle characteristics."""